name: Release automation for action
on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} 
